Replace packet+gui class searcher code with more stable annotation-based resolver
RS485/LogisticsPipes pull request #1126
Opened 2018-10-07 19:15 UTC by therealfarfetchd

Now it doesn't have to go through the file system to figure out which packets and guis to load, but instead uses Forge's ASMData system. This should never have any cases where it won't load, so any kind of fallback (that also has a chance of not working) isn't necessary. Downside is, all classes that should be loaded must be annotated with `@StaticResolve` (I automated this for all existing classes with `sed`, but when creating a new class you don't have to do that, of course).

This moves the packet and gui init code from the constructor to preInit because that's the place where you get the ASMData, which shouldn't affect anything as far as I could see (and a quick test confirmed that, also that the same classes were loaded as before).

2018-10-08 13:20 UTC, therealfarfetchd commented
That [WIP] was a false alarm, it works perfectly out of dev (when it didn't before), I just used the wrong build

2018-10-09 16:57 UTC, davboecki requested changes
Hey, Thanks this looks great just some minor but important detail. The Sets need to be changed Back to Lists and sorted. 
The reason is to make sure that on Server and Client the order is the same because assigned ids are not synced between Server and Client.

2018-10-09 16:57 UTC, davboecki commented on common/logisticspipes/network/NewGuiHandler.java
> +		// classes.sort(Comparator.comparing(it -> it));
This is needed. Best to make the Set into a List and change the comparator to Class::getName .

2018-10-09 16:57 UTC, davboecki commented on common/logisticspipes/network/PacketHandler.java
> +		// classes.sort(Comparator.comparing(it -> it));
Same as the other sort.

2018-10-09 16:59 UTC, therealfarfetchd commented
Ohhhhh, that is the reason why they are sorted. Yeah that makes complete sense now.

2018-10-09 17:35 UTC, davboecki approved these changes

2018-10-09 17:39 UTC, merged