Fixed improper fake Player creation. This should prevent fake player …
RS485/LogisticsPipes pull request #1197
Opened 2019-01-10 21:10 UTC by SonOfTheStars

…related crashes on crafting.

2019-01-10 21:24 UTC, dblsaiko submitted a review, later dismissed

2019-01-10 21:28 UTC, davboecki requested changes
Please check the comments I added. 

Have you ever heard of formatting?

2019-01-10 21:28 UTC, davboecki commented on common/logisticspipes/proxy/MainProxy.java
> +	public static FakePlayer getFakePlayer(World world, BlockPos pos) {
What is this supposed to do?

2019-01-10 21:28 UTC, davboecki commented on common/logisticspipes/proxy/MainProxy.java
> +	private static HashMap<Integer, LPFakePlayer> worldFakePlayer = new HashMap<>();
What about world unloading with the World reference inside the player? World leaking?

2019-01-10 22:39 UTC, SonOfTheStars commented on common/logisticspipes/proxy/MainProxy.java
> +	private static HashMap<Integer, LPFakePlayer> worldFakePlayer = new HashMap<>();
Should technically be handled by the forge implementation of FakePlayer that I am using here.

2019-01-10 22:39 UTC, SonOfTheStars commented on common/logisticspipes/proxy/MainProxy.java
> +	public static FakePlayer getFakePlayer(World world, BlockPos pos) {
On second thought that one really isnt neccessary. Since LP will likely not have any tiles that require the player at the tiles position.

2019-01-10 22:49 UTC, davboecki commented on common/logisticspipes/proxy/MainProxy.java
> +	private static HashMap<Integer, LPFakePlayer> worldFakePlayer = new HashMap<>();
https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/util/FakePlayerFactory.java
Forge handles that only for its own lists. 
And there is not much inside the class that could do that for us: https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/util/FakePlayerFactory.java

Just see this comment: https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/util/FakePlayerFactory.java#L54

2019-01-13 02:02 UTC, davboecki requested changes
Please check your formating again. There are a lot of places where you don't have a space between the if and the `(` as well as no spaces between the `)` and the `{`.

One last question: Are TileEntites automaticly registered on the Forge Event bus for subscribed events?

2019-01-13 02:02 UTC, davboecki commented on common/logisticspipes/entity/FakeNetServerHandler.java
> +
Please remove these empty lines everywhere, when there is content within the function itself as well

2019-01-13 02:02 UTC, davboecki commented on common/logisticspipes/entity/FakeNetServerHandler.java
> +
Same as above. Please look at other cases below as well. I'm not going to list them all.

2019-01-13 02:02 UTC, davboecki commented on common/logisticspipes/entity/FakePlayerLP.java
> +
Same here.

2019-01-13 02:02 UTC, davboecki commented on common/logisticspipes/proxy/MainProxy.java
> +	public static void OnWorldUnload(WorldEvent.Unload event){
Funciton names should start with a lower case letter.

2019-01-13 02:02 UTC, davboecki commented on common/logisticspipes/proxy/MainProxy.java
> +		val dimId = world.provider.getDimension();
Please don't use val in java code for LP.

2019-01-13 16:59 UTC, davboecki requested changes

2019-01-13 16:59 UTC, davboecki commented on common/logisticspipes/blocks/crafting/LogisticsCraftingTableTileEntity.java
> +		if (fake.world== worldEvent.getWorld())
Space before the `==`

2019-01-13 16:59 UTC, davboecki commented on common/logisticspipes/pipes/PipeBlockRequestTable.java
> +		if (fake.world== worldEvent.getWorld())
Space before the `==`

2019-01-13 17:19 UTC, merged