Fixed supplier pipe overflow issue
RS485/LogisticsPipes pull request #1229
Opened 2019-05-29 20:42 UTC by avlad171

Added a check at line 211 in ModuleActiveSupplier.java. The rest is just my comments and trying to figure out what goes wrong.

2019-05-29 23:46 UTC, theZorro266 commented on common/logisticspipes/modules/ModuleActiveSupplier.java
> +
Please revert any and all formatting changes.

2019-05-30 11:37 UTC, dblsaiko requested changes

2019-05-30 11:37 UTC, therealfarfetchd commented on common/logisticspipes/modules/ModuleActiveSupplier.java
> +		HashMap<ItemIdentifier, Integer> haveUndamaged = new HashMap<>();	//cam ca si have numa fara meta
Only write English comments

2019-05-30 11:37 UTC, therealfarfetchd commented on common/logisticspipes/modules/ModuleActiveSupplier.java
> +	{
Put braces on the same line (or in general, as @theZorro266 already said, keep the formatting consistent with the rest of the code)

2019-05-30 11:37 UTC, therealfarfetchd commented on common/logisticspipes/modules/ModuleActiveSupplier.java
> +		//System.out.println("Supplier: Start calculating supply request");
Don't leave these in, especially when there's already a log message saying the same thing right above

2019-05-30 11:37 UTC, therealfarfetchd commented on common/logisticspipes/utils/InventoryUtilFactory.java
> +import appeng.api.storage.IMEInventoryHandler;
Since nothing else is changed in this class, is this an unused import? If so, please remove

2019-05-30 11:37 UTC, therealfarfetchd commented on common/logisticspipes/utils/InventoryUtil.java
> +	public Map<ItemIdentifier, Integer> getItemsAndCount()
Nothing in this class has actually been changed functionality wise as far as I can see, so please revert

2019-05-30 11:52 UTC, theZorro266 commented
Merged #1228

2019-05-30 11:52 UTC, closed without merging