Add a config option for the number of moduleslots in a chassipipe
RS485/LogisticsPipes pull request #1321
Opened 2019-07-04 10:53 UTC by Noradly

I've made this pr because AE2 is IMHO far more powerful/cheaper and easier to craft while being less cool resulting in it being used more than it should(since this mods is far cooler).

Currently working
- Configurable number of slots in a chassipipe
- GUI creation at runtime (no idea if it's done 'correctly', but it's functional)
- The config settings (the default is the same as the current pipes)
- The modules & module options work in all the slots
- Reloading all textures

Nor working
-Nothing?

2019-07-05 20:48 UTC, davboecki commented
Have you looked at how our other GUIs are created?
We already have a system to dynamically create GUIs without any preconfigured texture. 
Other than that please take a look at our style for coding and especially for naming things.

2019-07-06 13:40 UTC, Noradly commented
I've removed my runtime texture creator and `drawGuiContainerBackgroundLayer` now creates the texture at runtime, it should all still work right.

2019-07-07 08:28 UTC, davboecki commented on common/logisticspipes/gui/GuiChassiPipe.java
> +		GL11.glTranslated(guiLeft, guiTop, 0);
Please don't use GL11 methods here, just put "guiLeft + 17" instead of 17 below, and so on...

2019-07-07 08:30 UTC, davboecki commented
And please look at the final diff and clean up all the changes that are not necessary, especially the ones where files will not change otherwise.

2019-07-07 08:50 UTC, Noradly commented
Should have changed al the things you asked for.

2019-07-11 22:29 UTC, bziemons requested changes
If I change the config option to only have 4 values: `[1,2,3,4]` this code would crash with an IndexOutOfBoundsException in the Mk5 Pipe. Please ensure the config option has always 5 entries and add an appropriate hint to the config option's description.

2019-07-11 22:29 UTC, theZorro266 commented on common/logisticspipes/gui/GuiChassiPipe.java
> +		for(int  i=0; i<_chassiPipe.getChassiSize(); i++)
styling

2019-07-11 22:29 UTC, theZorro266 commented on common/logisticspipes/network/guis/pipe/ChassiGuiProvider.java
> +		for(int i=0; i<_chassiPipe.getChassiSize(); i++){
styling

2019-07-11 22:29 UTC, theZorro266 commented on common/logisticspipes/config/Configs.java
> +	public static int [] CHASSI_SLOTS_ARRAY = {1,2,3,4,8};
please only one new-line before and after this field, styling

2019-07-11 22:29 UTC, theZorro266 commented on common/logisticspipes/config/Configs.java
> +		Configs.CHASSI_SLOTS_ARRAY = Configs.CONFIGURATION
again only one new-line before and after this

2019-07-11 22:29 UTC, theZorro266 commented on common/logisticspipes/gui/GuiChassiPipe.java
> +		for(int  i=0; i<_chassiPipe.getChassiSize(); i++)
styling

2019-07-11 22:29 UTC, theZorro266 commented on common/logisticspipes/gui/GuiChassiPipe.java
> +		for(int  i=0; i<_chassiPipe.getChassiSize() ; i++)
styling

2019-07-12 08:20 UTC, Noradly commented
Added your check and a check to make certain that the values are >=0. The issues above (should) have been resolved.

2019-07-12 10:16 UTC, theZorro266 commented
With styling I mean the usage of the formatter. The IntelliJ project has the formatter pre-configured and you can just run it.

Otherwise, what I meant was:
```diff
- for(int  i=0; i<_chassiPipe.getChassiSize() ; i++)
+ for (int i = 0; i < _chassiPipe.getChassiSize(); i++)
```

Please just stick with the project's existing code style.

2019-07-12 16:25 UTC, Noradly commented
Thanks, added an extra test to make certain that the entries are in ascending order (we use the last value to set the size of Slot[] upgradeslot in common/logisticspipes/gui/GuiChassiPipe.java).

2019-07-12 16:31 UTC, Noradly commented
Removed the first initialization of upgradeConfig since it was initialized twice.

2019-07-12 16:52 UTC, Noradly commented
I have found an issue though, the tooltip of a chassipipe says how many modules a pipe can hold, this text comes from the en_us.lang file and should be dependent on the actual number of modules a pipe can hold.

2019-07-12 17:00 UTC, theZorro266 commented on common/logisticspipes/config/Configs.java
> +		for(int i=0; i<Configs.CHASSI_SLOTS_ARRAY.length; i++){
styling here as well, please

2019-07-12 17:00 UTC, theZorro266 commented on common/logisticspipes/config/Configs.java
> +		for(int i=0; i<Configs.CHASSI_SLOTS_ARRAY.length-1; i++){
styling here as well, please

2019-07-12 17:05 UTC, theZorro266 commented
> I have found an issue though, the tooltip of a chassipipe says how many modules a pipe can hold, this text comes from the en_us.lang file and should be dependent on the actual number of modules a pipe can hold.

Add "by default" to the english language for now. If you like, you can add placeholders for language strings in another PR.

2019-07-12 17:35 UTC, bziemons approved these changes

2019-07-12 17:36 UTC, theZorro266 commented
Someone needs to test the changes and then this is good to merge :) Thanks for the work @Noradly

2019-07-14 12:18 UTC, Noradly commented
@theZorro266 I have been playing with this branch for a couple days now (since 9d4d41d) and all the bugs I've found have been fixed.

2019-07-27 11:15 UTC, davboecki commented
These changes don't work. While it appears to work for the GUI changes. As soon as you save and reload the world, the modules are removed except for the inv slots that are supposed to be there by default.

2020-05-18 01:01 UTC, bziemons commented
@davboecki that behavior actually happens with or without these changes. Just tested that.

I squashed and merged this code locally. I will try to find a fix for the mentioned problem.

2020-05-18 02:43 UTC, closed without merging

2020-05-18 02:45 UTC, bziemons commented
Also sorry for the misunderstanding. This should have been solved with a bit more communicating and testing, I think.