Fix crash with FinalNBTTagCompound
RS485/LogisticsPipes pull request #1369
Opened 2019-09-03 17:35 UTC by tom5454

Fixes crashes with items with NBT.

`Caused by: java.lang.UnsupportedOperationException
	at logisticspipes.utils.FinalNBTTagCompound.func_74782_a(FinalNBTTagCompound.java:75)
	at net.minecraft.nbt.NBTTagCompound.func_179237_a(NBTTagCompound.java:530)
	at logisticspipes.utils.FinalNBTTagCompound.<init>(FinalNBTTagCompound.java:14)
	at logisticspipes.utils.item.ItemIdentifier.get(ItemIdentifier.java:353)
        ....`

My crash with provider pipe and renamed item (in debugging environment):
[crash-2019-09-03_18.40.30-server.txt](https://github.com/RS485/LogisticsPipes/files/3570700/crash-2019-09-03_18.40.30-server.txt)
`

2019-09-03 19:03 UTC, therealfarfetchd commented
Whoops, my bad.

2019-09-03 19:06 UTC, dblsaiko requested changes
Whoops, my bad. But keep it AT free, please (make merge and all the others only throw after constructor execution, and keep the merge call)

2019-09-03 19:48 UTC, dblsaiko requested changes
Yup, like that. Please format the code, though.

2019-09-04 19:44 UTC, merged

2019-09-04 19:44 UTC, therealfarfetchd commented
:+1: